In [1]:
import cv2
import numpy as np

In [2]:
events = [i for i in dir(cv2) if 'EVENT' in i]
print(events)

['EVENT_FLAG_ALTKEY', 'EVENT_FLAG_CTRLKEY', 'EVENT_FLAG_LBUTTON', 'EVENT_FLAG_MBUTTON', 'EVENT_FLAG_RBUTTON', 'EVENT_FLAG_SHIFTKEY', 'EVENT_LBUTTONDBLCLK', 'EVENT_LBUTTONDOWN', 'EVENT_LBUTTONUP', 'EVENT_MBUTTONDBLCLK', 'EVENT_MBUTTONDOWN', 'EVENT_MBUTTONUP', 'EVENT_MOUSEHWHEEL', 'EVENT_MOUSEMOVE', 'EVENT_MOUSEWHEEL', 'EVENT_RBUTTONDBLCLK', 'EVENT_RBUTTONDOWN', 'EVENT_RBUTTONUP']


In [9]:
def click_event(event, x, y, flag, param):
    if event == cv2.EVENT_LBUTTONDOWN:
        print(x,', ',y)
        font = cv2.FONT_HERSHEY_SIMPLEX
        strXY = str(x)+', '+str(y)
        cv2.putText(img, strXY, (x, y), font, .5, (255, 255, 0), 2)
        cv2.imshow('image', img)
    if event == cv2.EVENT_RBUTTONDOWN:
        blue = img[x, y, 0]
        green = img[x, y, 1]
        red = img[x, y, 2]
        font = cv2.FONT_HERSHEY_SIMPLEX
        strBGR = str(blue)+', '+str(green)+', '+str(red)
        cv2.putText(img, strBGR, (x,y), font, .5, (0, 255, 255), 2)
        cv2.imshow('image', img)

#img = np.zeros((512, 512, 3), np.uint8)
img = cv2.imread('C:\\Users\\80SM01YGIH\\Anish\\CV101\\messi5 - Copy.jpg')
cv2.imshow('image', img)

cv2.setMouseCallback('image', click_event)

cv2.waitKey(0)
cv2.destroyAllWindows()

278 ,  209
278 ,  209
340 ,  138
382 ,  104
492 ,  154


In [40]:
def click_event_for_circle(event, x, y, flag, param):
    if event == cv2.EVENT_LBUTTONDOWN:
        cv2.circle(img, (x, y), 3, (0, 0, 255), -1)
        points.append((x, y))
        if len(points) >= 2:
            cv2.line(img, points[-2], points[-1], (255, 0, 0), 3)
        cv2.imshow('image', img)
        
img = cv2.imread('C:\\Users\\80SM01YGIH\\Anish\\CV101\\messi5 - Copy.jpg')
cv2.imshow('image', img)
points = []

cv2.setMouseCallback('image', click_event_for_circle)

cv2.waitKey(0)
cv2.destroyAllWindows()

In [8]:
def click_event_for_color(event, x, y, flag, param):
    if event == cv2.EVENT_LBUTTONDOWN:
        blue = img[x, y, 0]
        green = img[x, y, 1]
        red = img[x, y, 2]
        cv2.circle(img, (x, y), 3, (0, 0, 255), -1)
        mycolorImage = np.zeros((512, 512, 3), np.uint8)
        
        mycolorImage[:] = [blue, green, red]
        print(mycolorImage)
        
        cv2.imshow('colorimage', mycolorImage)
        
img = cv2.imread('C:\\Users\\80SM01YGIH\\Anish\\CV101\\messi5 - Copy.jpg')
cv2.imshow('image', img)

cv2.setMouseCallback('image', click_event_for_color)

cv2.waitKey(0)
cv2.destroyAllWindows()

[[[ 42 112  71]
  [ 42 112  71]
  [ 42 112  71]
  ...
  [ 42 112  71]
  [ 42 112  71]
  [ 42 112  71]]

 [[ 42 112  71]
  [ 42 112  71]
  [ 42 112  71]
  ...
  [ 42 112  71]
  [ 42 112  71]
  [ 42 112  71]]

 [[ 42 112  71]
  [ 42 112  71]
  [ 42 112  71]
  ...
  [ 42 112  71]
  [ 42 112  71]
  [ 42 112  71]]

 ...

 [[ 42 112  71]
  [ 42 112  71]
  [ 42 112  71]
  ...
  [ 42 112  71]
  [ 42 112  71]
  [ 42 112  71]]

 [[ 42 112  71]
  [ 42 112  71]
  [ 42 112  71]
  ...
  [ 42 112  71]
  [ 42 112  71]
  [ 42 112  71]]

 [[ 42 112  71]
  [ 42 112  71]
  [ 42 112  71]
  ...
  [ 42 112  71]
  [ 42 112  71]
  [ 42 112  71]]]
