In [2]:
import numpy as np
import cv2

In [6]:
cap = cv2.VideoCapture('C:\\Users\\80SM01YGIH\\Anish\\CV101\\slow_traffic_small.mp4')

ret, frame = cap.read()

x, y, w, h = 300, 200, 100, 50

track_window = (x, y, w, h)

roi = frame[y: y+h, x: x+w]

hsv_roi = cv2.cvtColor(roi, cv2.COLOR_BGR2HSV)

mask = cv2.inRange(hsv_roi, np.array((0., 60., 32.)), np.array((180., 255., 255.)))

roi_hist = cv2.calcHist([hsv_roi], [0], mask, [180], [0, 180])

cv2.normalize(roi_hist, roi_hist, 0, 255, cv2.NORM_MINMAX)

term_crit = (cv2.TERM_CRITERIA_EPS| cv2.TERM_CRITERIA_COUNT, 10, 1)

cv2.imshow('roi', roi)

while(1):
    ret, frame = cap.read()
    if ret == True:
        hsv = cv2.cvtColor(frame, cv2.COLOR_BGR2HSV)
        
        dst = cv2.calcBackProject([hsv], [0], roi_hist, [0, 180], 1)
        
        ret, track_window = cv2.CamShift(dst, track_window, term_crit)
        
        #x, y, w, h = track_window
        
        #final_image = cv2.rectangle(frame, (x, y), (x+w, y+h), 255, 3)
        
        pts = cv2.boxPoints(ret)
        
        print(pts)
        
        pts = np.int0(pts)
        
        final_image = cv2.polylines(frame, [pts], True, (0, 255, 0), 2)
        
        cv2.imshow('dst', dst)
        
        cv2.imshow('final_image', final_image)
        
        k = cv2.waitKey(30) & 0xFF
        
        if k == ord('q'):
            break
    else:
        break
        
cap.release()
cv2.destroyAllWindows()

[[315.2072  187.89851]
 [398.84894 194.02357]
 [396.7928  222.10149]
 [313.15106 215.97643]]
[[319.61652 191.50002]
 [394.9226  196.85487]
 [393.38348 218.49998]
 [318.0774  213.14513]]
[[321.63092 192.25986]
 [394.95935 198.23984]
 [393.36908 217.74014]
 [320.04065 211.76016]]
[[320.7584  193.52069]
 [393.6008  198.82953]
 [392.2416  217.47931]
 [319.3992  212.17047]]
[[321.82224 194.5947 ]
 [393.54575 199.8956 ]
 [392.17776 218.4053 ]
 [320.45425 213.1044 ]]
[[320.9231  193.14307]
 [399.94702 200.96628]
 [398.0769  219.85693]
 [319.05298 212.03372]]
[[321.89383 193.63565]
 [400.0682  200.7232 ]
 [398.10617 222.36435]
 [319.9318  215.2768 ]]
[[321.41946 192.9755 ]
 [401.00034 200.98657]
 [398.58054 225.0245 ]
 [318.99966 217.01343]]
[[323.20358 194.14804]
 [403.91214 201.94138]
 [401.79642 223.85196]
 [321.08786 216.05862]]
[[321.38187 193.90353]
 [404.7753  197.7038 ]
 [403.61813 223.09647]
 [320.2247  219.2962 ]]
[[317.10464 194.3696 ]
 [406.2131  195.4097 ]
 [405.89536 222.6304 ]
 

[[342.88327 198.88121]
 [522.0847  192.65297]
 [524.1167  251.11879]
 [344.91528 257.34705]]
[[347.2617  200.74075]
 [516.74927 191.34427]
 [519.7383  245.25925]
 [350.25073 254.65573]]
[[340.9721  203.49875]
 [520.9445  190.20792]
 [525.0279  245.50125]
 [345.05548 258.79208]]
[[344.5982  200.86084]
 [524.9692  192.78809]
 [527.4018  247.13916]
 [347.03082 255.21191]]
[[343.74216 201.1772 ]
 [530.54083 192.34685]
 [533.2578  249.8228 ]
 [346.45917 258.65314]]
[[349.54086 201.17953]
 [530.07574 190.36075]
 [533.4591  246.82047]
 [352.92426 257.63925]]
[[346.93326 202.92288]
 [528.31744 190.83197]
 [532.0668  247.07712]
 [350.68256 259.16803]]
[[352.45227 201.37921]
 [532.6931  192.2515 ]
 [535.5477  248.62079]
 [355.3069  257.7485 ]]
[[350.19757 202.90611]
 [535.64264 192.84633]
 [538.8024  251.09389]
 [353.35736 261.1537 ]]
[[352.7795  200.30261]
 [534.46356 191.67062]
 [537.22046 249.69739]
 [355.53644 258.32938]]
[[355.9498  199.35732]
 [539.7882  192.55049]
 [542.0502  253.64268]
 

[[564.82996 364.8094 ]
 [598.9994  205.56696]
 [653.17004 217.19061]
 [619.0006  376.43304]]
[[571.45135 366.88153]
 [599.9996  214.87376]
 [654.54865 225.11847]
 [626.0004  377.12622]]
[[579.70557 370.74115]
 [597.5679  226.2464 ]
 [654.29443 233.25885]
 [636.4321  377.7536 ]]
[[587.31714 365.3786 ]
 [599.34424 243.55305]
 [650.68286 248.6214 ]
 [638.65576 370.44696]]
[[594.44745 362.25928]
 [602.6932  256.25134]
 [647.55255 259.74072]
 [639.3068  365.74866]]
[[644.4025  273.45255]
 [647.03326 359.27737]
 [605.5975  360.54745]
 [602.96674 274.72263]]
[[642.531   283.52274]
 [648.0348  352.5623 ]
 [611.469   355.47726]
 [605.9652  286.4377 ]]
[[640.484   289.63007]
 [645.52185 348.99323]
 [617.516   351.36993]
 [612.47815 292.00677]]
[[620.39264 343.7222 ]
 [622.71954 288.39926]
 [643.60736 289.2778 ]
 [641.28046 344.60074]]
[[624.19    343.0985 ]
 [630.6064  294.16998]
 [643.81    295.9015 ]
 [637.3936  344.83002]]
[[642.0455  306.58856]
 [644.21747 346.74823]
 [631.9545  347.41144]
 

[[509.86377  -28.824528]
 [678.0252    62.502655]
 [612.1362   183.82452 ]
 [443.9748    92.497345]]
[[508.3496   -27.67657 ]
 [677.1406    63.691166]
 [611.6504   184.67657 ]
 [442.85938   93.30884 ]]
[[506.64346  -28.8988  ]
 [676.71466   63.176   ]
 [611.35657  183.8988  ]
 [441.28534   91.824005]]
[[508.3357   -27.400566]
 [678.08826   67.16744 ]
 [611.6643   186.40057 ]
 [441.91174   91.83256 ]]
[[505.18414  -31.429688]
 [675.1268    57.41382 ]
 [610.81586  180.42969 ]
 [440.87323   91.58618 ]]
[[505.09988  -36.042477]
 [678.51      60.114765]
 [610.90015  182.04248 ]
 [437.49      85.88524 ]]
[[502.35715 -38.69408]
 [675.1551   54.45744]
 [607.6428  179.69408]
 [434.8449   86.54256]]
[[499.91052  -39.05381 ]
 [677.02136   54.953876]
 [610.0895   181.0538  ]
 [432.97864   87.04613 ]]
[[489.5921   -41.390255]
 [674.72626   47.288208]
 [612.4079   177.39026 ]
 [427.27374   88.71179 ]]
[[491.47153  -43.903652]
 [679.593     53.875954]
 [612.52844  182.90366 ]
 [424.40698   85.12405 ]